apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd  # Namespace where Argo CD will manage resources
spec:
  project: default  # Argo CD project name
  source:
    repoURL: https://github.com/vikashsingh740/vikash-test.git
    path: dev
    targetRevision: HEAD  # Git branch, tag, or commit SHA to deploy
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server URL
    namespace: myapp  # Namespace where resources will be deployed
  
  syncPolicy:
    syncOptions:
    - Createnamespace=true
    automated:
      prune: true
      selfHeal: true
